projects:
  - owner: interchainio
    project_number: 3
    story_type_field_id: PVTSSF_lADOAsuzxc4AkKP5zgcaQoo
    status_field_id: PVTSSF_lADOAsuzxc4AkKP5zgcaQn8
    epic_option_id: 282f80fd
    status_option_mapping:
      "â˜ƒï¸ Icebox": d958ab90
      "ğŸ“‹ Backlog": f75ad846
      "ğŸ¤¸â€â™‚ï¸ In Progress": 47fc9ee4
      "ğŸ‘€ Waiting / In review": 2ab45224
      "ğŸ¥³ Done": 98236657

  - owner: strangelove-ventures
    project_number: 58
    story_type_field_id: PVTSSF_lADOBTYxNs4AkKTLzgcaTbk
    status_field_id: PVTSSF_lADOBTYxNs4AkKTLzgcaTa4
    epic_option_id: 282f80fd
    status_option_mapping:
      "â˜ƒï¸ Icebox": d958ab90
      "ğŸ“‹ Backlog": f75ad846
      "ğŸ¤¸â€â™‚ï¸ In Progress": 47fc9ee4
      "ğŸ‘€ Waiting / In review": 2ab45224
      "ğŸ¥³ Done": 98236657

  - owner: cosmos
    project_number: 28
    story_type_field_id: PVTSSF_lADOAAN9684AKm_5zgGm5QY
    status_field_id: PVTSSF_lADOAAN9684AKm_5zgGm46I
    epic_option_id: 282f80fd
    status_option_mapping:
      "ğŸ©¹ F1: Triage": 6cc47a2c
      "ğŸ¤” F1: Investigate": f155678b
      "ğŸ“¥ F2: Todo": 8cf50de9
      "ğŸ›‘ F3: OnHold": f75ad846
      "ğŸ— F3: InProgress": 47fc9ee4
      "ğŸ‘€ F3: InReview": a066252b
      "ğŸ‘ F4: Assessment": f397b409
      "âœ… Done": 98236657
